### ISSUE TITLE
Always getting 0 samples 

### ISSUE THREAD

**Issue by mdsantosdev** [gin-contrib/pprof#10]
Hello guys, I'm trying to profile my gin application, I've the default ping endpoint.
This is my code:
```
func App() *gin.Engine {
	r := gin.Default()
	pprof.Register(r, "debug/pprof")

	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})

	return r;
}
```
I'm using 

> go tool pprof http://localhost/debug/pprof/profile

Which after 30s of me doing a lot of request to my ping endpoint responds :

> Type: cpu
> Time: Nov 21, 2018 at 12:47pm (-05)
> Duration: 30s, Total samples = 0 
> No samples were found with the default sample value type.
> Try "sample_index" command to analyze different sample values.
> Entering interactive mode (type "help" for commands, "o" for options)
> (pprof) 

After those 30 seconds I'm getting 0 samples which doesn't make any sense. and If I do **web** in **pprof** command line I get an empty svg like this:
<img width="167" alt="screen shot 2018-11-21 at 12 55 12" src="https://user-images.githubusercontent.com/32743338/48859666-b4d71900-ed8c-11e8-9150-a0fcc9b46ed3.png">

Am I doing something wrong?

**Comment by YJinHai** [comment]
my too

**Comment by YJinHai** [comment]
@thinkerou

**Comment by YJinHai** [comment]
@dalu

**Comment by dalu** [comment]
stop pinging me

**Comment by drsect0r** [comment]
I have the same issue on go1.12.

I have tried with pprof.StartCPUProfile(file) to create a profile file, with the inbuild _ "net/http/pprof" and with the example within this repository. I've debugged a Gin application before but can't seem to get it working at the moment anymore.

**Comment by crodwell** [comment]
I suspect you're not throwing enough requests at the API to be sampled by pprof.

**Comment by Kevinello** [comment]
is there any progress here? i got the same issue in go1.19 gin v1.7.4
