### ISSUE TITLE
Could we please cut a new release v1.4.0?

### ISSUE THREAD

**Issue by kskewes-sf** [gin-contrib/pprof#32]
Thank you for the recent v1.3.0 release.

There are still a little over 2 years of changes to master branch since `v1.3.0` though.  https://github.com/gin-contrib/pprof/compare/v1.3.0...master 

These changes include updating the gin version from `v1.6.2` which pulls in an older `x/text` library that has a couple of CVE's. :)

**Comment by appleboy** [comment]
https://github.com/gin-contrib/pprof/releases/tag/v1.4.0
